
- name: Install msys2
  win_chocolatey:
    name: msys2
    version: '20160719.1.1'
    state: present
#    ignore_checksums: yes

- import_tasks: pacman.yml

#- name: Install mingw
#  win_chocolatey:
#    name: mingw
#    version: '5.3.0'
#    state: present

#TODO do below by hand because of wrong network and checksum
#Please install it in C:\tools\MinGW like chocolatey would have done it
#- name: Install mingw-get
#  win_chocolatey:
#    name: mingw-get
#    version: '1.0.2'
#    state: present

#See C:\tools\MinGW\bin\mingw-get.exe
#mingw-get install gcc g++ mingw32-make gdb objc msys-base

#mingw-get install msys-wget msys-zip msys-unzip

- name: Install cygwin
  win_chocolatey:
    name: cygwin
    version: '2.9.0'
    state: present

- name: Install cyg-get
  win_chocolatey:
    name: cyg-get
    version: '1.2.1'
    state: present

- name: Install cyg-get ansible required packages
  win_shell: cyg-get python python-paramiko python-crypto gcc-g++ wget openssh python-setuptools vim openssl-devel libsasl2 ca-certificates python-setuptools python-openssl curl

- name: Install cyg-get git packages
  win_shell: cyg-get git gitk git-completion
  
- name: Install cyg-get editor required packages
  win_shell: cyg-get vim nano

- name: Install cyg-get packages
  win_shell: cyg-get ksh binutils util-linux ncurses-demo diffutils openssl

- name: Install cyg-get rsync ssh packages
  win_shell: cyg-get rsync openssh

- name: Install cyg-get archive packages
  win_shell: cyg-get zip unzip

#- name: "Link 1 for bash between mingw and msys"
#  win_command: 'mklink \"C:\tools\msys64\mingw64\bin\bash.exe\" \"C:\tools\msys64\usr\bin\bash.exe\"'
#    
#- name: "Link 2 for sh between mingw and msys"
#  win_command: 'mklink \"C:\tools\msys64\mingw64\bin\sh.exe\" \"C:\tools\msys64\usr\bin\sh.exe\"'

- name: Install X windows
  win_chocolatey:
    name: vcxsrv
    version: '1.19.3.1'
    state: present

#- name: Install gnuwin
#  win_chocolatey:
#    name: gnuwin
#    version: '0.6.3.1'
#    state: present

- name: Install pywin32 for scons parallel
  win_chocolatey:
    name: pywin32
    version: '219.0'
    state: present
#    ignore_checksums: yes
