---

- name: Install msys2
  win_chocolatey:
    name: msys2
    version: '20180531.1.0.0'
    state: present
    force: yes
  ignore_errors: true
#    ignore_checksums: yes

- import_tasks: pacman.yml

#- name: Install mingw
#  win_chocolatey:
#    name: mingw
#    version: '5.3.0'
#    state: present

#TODO do below by hand because of wrong network and checksum
#Please install it in C:\tools\MinGW like chocolatey would have done it
#- name: Install mingw-get
#  win_chocolatey:
#    name: mingw-get
#    version: '1.0.2'
#    state: present

#See C:\tools\MinGW\bin\mingw-get.exe
#mingw-get install gcc g++ mingw32-make gdb objc msys-base

#mingw-get install msys-wget msys-zip msys-unzip

- name: Install cygwin
  win_chocolatey:
    name: cygwin
    version: '2.11.2.20181212'
    state: present

#- import_tasks: cygwin.yml

- name: Install X windows
  win_chocolatey:
    name: vcxsrv
    version: '1.19.3.1'
    state: present

#- name: Install gnuwin
#  win_chocolatey:
#    name: gnuwin
#    version: '0.6.3.1'
#    state: present


- name: Install pywin32 for scons parallel
  win_chocolatey:
    name: pywin32
    version: '219.0'
    state: present
  ignore_errors: true

#export PATH="$PATH:/c/tools/msys64/mingw32/bin"

- name: Ensure that mingw32 are present on the global system path, and in the specified order (OLD)
  win_path:
    elements:
    - 'C:\tools\msys64\mingw32\bin'

- name: Ensure that Msys64 are present on the global system path, and in the specified order (OLD)
  win_path:
    elements:
    - 'C:\tools\msys64'
    - 'C:\tools\msys64\usr\bin'

- name: Ensure that Msys64 are present on the global system path, and in the specified order (NEW)
  win_path:
    elements:
    - 'C:\msys64'
    - 'C:\msys64\usr\bin'

# TODO in order to test, open a cmd prompt and type bash
