---

- name: Install X windows
  win_chocolatey:
    name: vcxsrv
    version: '1.19.3.1'
    state: present

#- name: Install gnuwin
#  win_chocolatey:
#    name: gnuwin
#    version: '0.6.3.1'
#    state: present
