
- name: Install activeperl
  win_chocolatey:
    name: activeperl
    version: '5.24.1.2402'
    state: present

- name: Install msys2
  win_chocolatey:
    name: msys2
    version: '20160719.1.1'
    state: present

- name: Install mingw
  win_chocolatey:
    name: mingw
    version: '5.3.0'
    state: present

- name: Install gnuwin
  win_chocolatey:
    name: gnuwin
    version: '0.6.3.1'
    state: present
