---

- name: Install windirstat
  win_chocolatey:
    name: windirstat
    version: '1.1.2.20161210'
    state: present
#    force: yes
  ignore_errors: true
  tags:
    - package
    - common
    - windirstat
    - utility
    - debug
    - vm # do not install on docker image
    
- name: Install treesizefree
  win_chocolatey:
    name: treesizefree
    version: '4.5.2'
    state: present
  ignore_errors: true
  tags:
    - package
    - common
    - treesizefree
    - utility
    - debug
    - vm # do not install on docker image
    
#- name: Install pscx
#  win_chocolatey:
#    name: pscx
#    version: 'TODO'
#    state: present
