
- name: Install utility packages
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
  - pscx
  - windirstat

- name: Install container packages
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
  - docker-desktop
  - docker-cli
  - kubernetes-helm
  - kubernetes-cli
