
- name: Install graphviz
  win_chocolatey:
    name: graphviz
    version: '2.38.0.1'
    state: present
  ignore_errors: true
    
#- name: Install gnuplot
#  win_chocolatey:
#    name: gnuplot
#    version: '5.0.5'
#    state: present
    
- name: Install doxygen
  win_chocolatey:
    name: doxygen.install
    version: '1.8.11'
    state: present
  ignore_errors: true

#choco install vcpython27

#choco install vcredist-all
#- name: Install vcredist2017
#  win_chocolatey:
#    name: vcredist2017
#    version: '14.11.25325.0'
#    state: present

#choco install visualstudio2017-workload-nativecrossplat --package-parameters "--productId Microsoft.VisualStudio.Product.Enterprise --channelId VisualStudio.15.Release --includeOptional"

#- name: Install visualstudio2017community
#  win_chocolatey:
#    name: visualstudio2017community
#    version: '15.2.26430.20170605'
#    state: present 

- name: Install microsoft-build-tools
  win_chocolatey:
    name: microsoft-build-tools
    version: '15.0.26228.0'
    state: present

- name: Install visualstudio2017buildtools
  win_chocolatey:
    name: visualstudio2017buildtools
    version: '15.2.26430.20170605'
    state: present

- name: Install windbg
  win_chocolatey:
    name: windbg
    version: '10.0.10586.15'
    state: present

- name: Install dependencywalker
  win_chocolatey:
    name: dependencywalker
    version: '2.2.6000.8'
    state: present

#- name: "Enable .net"
#  win_shell: "Import-Module ServerManager; Add-WindowsFeature as-net-framework"

#- name: "Install Visual Studio 2008"
#  include: visualstudio-2008.yml
#  tags:
#    - vs
#    - vs2008
#
#- name: "Install Visual Studio 2012"
#  include: visualstudio-2012.yml
#  tags:
#    - vs
#    - vs2012
