---

- name: Install graphviz
  win_chocolatey:
    name: graphviz
    version: '2.38.0.1'
    state: present
  ignore_errors: true

#- name: Install gnuplot
#  win_chocolatey:
#    name: gnuplot
#    version: '5.0.5'
#    state: present

- name: Install doxygen
  win_chocolatey:
    name: doxygen.install
    version: '1.8.11'
    state: present
  ignore_errors: true

#choco install vcpython27

- name: Install windbg
  win_chocolatey:
    name: windbg
    version: '10.0.10586.15'
    state: present

- name: Install dependencywalker
  win_chocolatey:
    name: dependencywalker
    version: '2.2.6000.9'
    state: present

#- name: "Enable .net"
#  win_shell: "Import-Module ServerManager; Add-WindowsFeature as-net-framework"

- name: "Install Visual Studio 2017"
  import_tasks: visualstudio-2017.yml
  tags:
    - vs
    - vs2017
