
- name: "Download curl"
  win_get_url:
    url: "https://dl.uxnr.de/build/curl/curl_winssl_msys2_mingw64_stc/curl-7.53.1/curl-7.53.1.zip"
    dest: c:\curl-7.53.1.zip
    
- name: "Unzip curl"
  win_unzip:
    src: C:\curl-7.53.1.zip
    remote_src: True
    dest: C:\curl\
    
- name: "Delete curl zip"
  win_file:
    path: C:\curl-7.53.1.zip
    state: absent
    
- name: "Update PATH"
  win_path:
    elements: C:\curl\src
    scope: machine
    state: present
