---
#TODO
##Dependency Walker
#Download Dependency Walker from http://www.dependencywalker.com/
##Process Tools
#Download Process Explorer from http://technet.microsoft.com/en-gb/sysinternals/bb896653
#Download Process Dump from http://technet.microsoft.com/en-us/sysinternals/dd996900
#Download List DLLs from http://technet.microsoft.com/en-us/sysinternals/bb896656

- name: Install MobaXterm packages
  win_chocolatey:
    name: "MobaXterm"
    version: "21.1"
    state: present
  #    force: yes
  ignore_errors: true
  tags:
    - package
    - ssh
    - debug

- name: Install windbg
  win_chocolatey:
    name: windbg
    version: "10.0.10586.15"
    state: present
  ignore_errors: true
  tags:
    - package
    - windbg
    - debug
