
- name: Install notepadplusplus
  win_chocolatey:
    name: notepadplusplus.install
    version: '7.5.1'

- name: Install atom
  win_chocolatey:
    name: atom
    version: '1.0.7'

- name: Install meld
  win_chocolatey:
    name: meld
    version: '3.16.2'

#cinst nano

- name: Install nano
  win_chocolatey:
    name: nano
    version: '2.5.3'
