
- name: Install git
  win_chocolatey:
    name: git
    version: '2.28.0'
    state: present
    force: yes

- name: Install tortoisegit (used for diff)
  win_chocolatey:
    name: tortoisegit
    version: '2.8.0.0'
    state: present
    force: yes
  ignore_errors: true

#- name: Install git-credential-manager-for-windows
#  win_chocolatey:
#    name: git-credential-manager-for-windows
#    version: '1.12.0'

- name: "Add .gitconfig to jenkins user"
  copy:
   # content: "# Ansible managed"
   content: " "
   dest: C:\Users\{{ jenkins_user }}\.gitconfig

- name: "Disable git ssl verification"
  win_command: "git config --global http.sslVerify false"
  ignore_errors: true # could not lock config file /home/jenkins/.gitconfig: No such file or directory

# With mingw (on windows) force core.autocrlf true (it will not replace LF by CR LF)
# make sure .gitattributes HAVE *.files text eol=lf
#- name: "Enable autocrlf for git "
#  win_command: "git config --system core.autocrlf true"
#  ignore_errors: true # could not lock config file /home/jenkins/.gitconfig: No such file or directory

- name: "Enable longpaths for git"
  win_command: "git config --system core.longpaths true"
  ignore_errors: true # could not lock config file /home/jenkins/.gitconfig: No such file or directory

- name: "User email for git"
  win_command: "git config --global user.email \"{{ shell_git_email }}\""
  ignore_errors: true # could not lock config file /home/jenkins/.gitconfig: No such file or directory

- name: "User name for git"
  win_command: "git config --global user.name \"{{ shell_git_name }}\""
  ignore_errors: true # could not lock config file /home/jenkins/.gitconfig: No such file or directory

#- name: "Link 1 between mingw and git"
#  win_command: 'mklink "C:\Program Files\Git\cmd\nohup.exe" "C:\Program Files\git\usr\bin\nohup.exe"'
#
#- name: "Link 2 between mingw and git"
#  win_command: 'mklink "C:\Program Files\Git\cmd\msys-2.0.dll" "C:\Program Files\git\usr\bin\msys-2.0.dll"'
#
#- name: "Link 3 between mingw and git"
#  win_command: 'mklink "C:\Program Files\Git\cmd\msys-iconv-2.dll" "C:\Program Files\git\usr\bin\msys-iconv-2.dll"'
#
#- name: "Link 4 between mingw and git"
#  win_command: 'mklink "C:\Program Files\Git\cmd\msys-intl-8.dll" "C:\Program Files\git\usr\bin\msys-intl-8.dll"'

#TODO copy .gitconfig to C:\tools\misys64\home\fru
- name: Copy .gitconfig to misys64
  win_copy:
    src: C:\Users\{{ jenkins_user }}\.gitconfig
    dest: C:\tools\misys64\home\{{ jenkins_user }}
    force: True
    remote_src: False
    register: out
  ignore_errors: true # could not lock config file /home/jenkins/.gitconfig: No such file or directory

- debug: var=out.stdout_lines
