
#- name: Install jdk7
#  win_chocolatey:
#    name: jdk7
#    version: '7.0.80'
#    state: present

#choco install jdk8.portable --version 8.0.201 -y
#- name: Install jdk8
#  win_chocolatey:
#    name: jdk8.portable
#    version: '{{ java_version }}'
#    state: present
#install will be in C:\tools\jdk_8u202

#choco install jdk8 --version 8.0.201 -y
- name: Install jdk8
  win_chocolatey:
    name: jdk8
    version: '{{ java_version }}'
    state: present
#for non portable install will be in C:\Program Files\Java\jdk1.8.0_201

- name: Install ant
  win_chocolatey:
    name: ant
    version: '1.10.1'
    state: present

- name: Install maven
  win_chocolatey:
    name: maven
    version: '3.5.0'
    state: present

#TODO by hand
#Replace Path Environment variable from C:\ProgramData\Oracle\Java\javapath by %JAVA_HOME%\bin
#Replace regedit Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion' but 1.7
#Replace regedit Registry key 'Software\JavaSoft\Java Development Kit'\CurrentVersion' but 1.7

- name: Ensure that C:\Program Files\Java\jdk1.8.0_201 JAVA_HOME is on the current user's CLASSPATH
  win_path:
    name: JAVA_HOME
    elements: C:\Program Files\Java\jdk1.8.0_201
    scope: user
#    state: absent

- name: Ensure that jdk7 are present on the global system path, and in the specified order
  win_path:
    elements:
    - '%JAVA_HOME%\bin'
    scope: user

#Instead run the java web start by hand
#javaws -viewer
#javaws  "slave-agent.jnlp"

#Add -noCertificateCheck to the jenkins-slave.xml

# Generate id_rsa from MSYS2
# Copy it from C:\msys64\home\jenkins or C:\tools\msys64\home\jenkins to the user
# Add the key to Bitbucket
# Test doing git clone ssh://todo

# Change jenkins service to start as Log on as -> This account
