
#- name: Install jdk7
#  win_chocolatey:
#    name: jdk7
#    version: '7.0.79'
#    state: present
    
- name: Install jdk8
  win_chocolatey:
    name: jdk8
    version: '8.0.144'
    state: present
    
- name: Install ant
  win_chocolatey:
    name: ant
    version: '1.10.1'
    state: present
        
- name: Install maven
  win_chocolatey:
    name: maven
    version: '3.5.0'
    state: present

#TODO by hand
#Replace Path Environment variable from C:\ProgramData\Oracle\Java\javapath by %JAVA_HOME%\bin
#Replace regedit Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion' bu 1.7
#Replace regedit Registry key 'Software\JavaSoft\Java Development Kit'\CurrentVersion' bu 1.7
