
- name: Install kubernetes cli packages
  win_chocolatey:
    name: 'kubernetes-cli'
    version: '1.18.5'
    state: present

- name: Install helm packages
  win_chocolatey:
    name: 'kubernetes-helm'
    version: '3.2.4'
    state: present
