
- name: Install msys2
  win_chocolatey:
    name: msys2
    version: '20180531.1.0.0'
    state: present
    force: yes
  ignore_errors: true
#    ignore_checksums: yes

- import_tasks: pacman.yml

# Below is no more needed as it is installed with msys2
#- name: Install mingw
#  win_chocolatey:
#    name: mingw
#    version: '5.3.0'
#    state: present

# TODO replace mingw by
#- name: SEP - Install - Copy the new msys64 directory (Windows)
#  win_get_url:
#    url: "https://albandrieu.com/download/msys/msys64.zip"
#    dest: "C:\\tools\\msys64.zip"
#    checksum: "TODO"
#    checksum_algorithm: sha1
#    when: folder_utils.stat.exists == true

- name: Check HASH
  win_shell: |
    Get-FileHash -Algorithm SHA1 'C:\tools\msys64.zip' | Select Hash

#- name: SEP - Install - Copy the new msys64 directory (Windows)
#  win_get_url:
#    url: "https://albandrieu.com/download/msys/jenkins.zip"
#    dest: "C:\\tools\\msys64\\home\\jenkins.zip"
#    checksum: "TODO"
#    checksum_algorithm: sha1
#    when: folder_utils.stat.exists == true

#- name: Check HASH
#  win_shell: |
#    Get-FileHash -Algorithm SHA1 'C:\tools\msys64\home\jenkins.zip' | Select Hash

#TODO do below by hand because of wrong network and checksum
#Please install it in C:\tools\MinGW like chocolatey would have done it
#- name: Install mingw-get
#  win_chocolatey:
#    name: mingw-get
#    version: '1.0.2'
#    state: present

#See C:\tools\MinGW\bin\mingw-get.exe
#mingw-get install gcc g++ mingw32-make gdb objc msys-base

#mingw-get install msys-wget msys-zip msys-unzip

- name: Install cygwin
  win_chocolatey:
    name: cygwin
    version: '2.11.2.20181212'
    state: present

#TODO
#- name: "Link 1 to Older mingw32 such as gcc 4.9.0"
#  win_command: mklink /j "C:\tools\msys64\mingw32" "C:\tools\mingw32"'

#export PATH="$PATH:/c/tools/msys64/mingw32/bin"

- name: Ensure that mingw32 are present on the global system path, and in the specified order (OLD)
  win_path:
    elements:
    - 'C:\\tools\\msys64\\mingw32\\bin'

- name: Ensure that Msys64 are present on the global system path, and in the specified order (OLD)
  win_path:
    elements:
    - 'C:\\tools\\msys64'
    - 'C:\\tools\\msys64\\usr\\bin'

- name: Ensure that Msys64 are present on the global system path, and in the specified order (NEW)
  win_path:
    elements:
    - 'C:\\msys64'
    - 'C:\\msys64\\usr\\bin'

# TODO in order to test, open a cmd prompt and type bash

#- name: Enable Microsoft-Windows-Subsystem-Linux
#  win_shell: |
#    Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
