---
#Called by pacman
#- import_tasks: pacman.yml

# Below no more needed, we are adding our own for old X compil on 32 bits
- name: Install msys2
  win_chocolatey:
    name: msys2
    version: "20210604.0.0"
    package_params: '"/NoUpdate /NoPath /InstallDir:C:\tools\msys64-new"'
    state: present
    force: yes
  ignore_errors: true
  tags:
    - package
    #- mingw
    - msys2-native
    - build
    #- vm # do not install on docker image

#- name: Copy msys64
#  ansible.windows.win_copy:
#    src: C:\tools\msys64
#    dest: C:\tools\msys64-new
#    remote_src: yes

# Below is no more needed as it is installed with msys2
#- name: Install mingw
#  win_chocolatey:
#    name: mingw
#    version: '5.3.0'
#    state: present

# TODO replace mingw by
#- name: MSYS - Install - Copy the new msys64 directory (Windows)
#  win_get_url:
#    url: "https://albandrieu.com/download/msys/msys64.zip"
#    dest: "C:\\tools\\msys64.zip"
#    checksum: "TODO"
#    checksum_algorithm: sha1
#  tags:
#    - package
#    - msys2
#    - custom
#    - build
#    #- vm # do not install on docker image

#- name: Check HASH
#  win_shell: |
#    Get-FileHash -Algorithm SHA1 'C:\tools\msys64.zip' | Select Hash
#  tags:
#    - package
#    - msys2
#    - custom
#    - build
#    #- vm # do not install on docker image

- name: Install PSCX
  win_psmodule:
    name: Pscx
    state: present
  tags:
    - package
    - pscx
    - custom
    - unzip
    - build
    #- vm # do not install on docker image

#- name: MSYS - Install - Copy the new msys64 directory (Windows)
#  win_get_url:
#    url: "https://albandrieu.com/download/msys/jenkins.zip"
#    dest: "C:\\tools\\msys64\\home\\jenkins.zip"
#    checksum: "TODO"
#    checksum_algorithm: sha1
#    when: folder_utils.stat.exists == true
#  tags:
#    - package
#    - msys2
#    - custom
#    - build
#    #- vm # do not install on docker image

#- name: Check HASH
#  win_shell: |
#    Get-FileHash -Algorithm SHA1 'C:\tools\msys64\home\jenkins.zip' | Select Hash
#  tags:
#    - package
#    - msys2
#    - custom
#    - build
#    #- vm # do not install on docker image

#TODO do below by hand because of wrong network and checksum
#Please install it in C:\tools\MinGW like chocolatey would have done it
#- name: Install mingw-get
#  win_chocolatey:
#    name: mingw-get
#    version: '1.0.2'
#    state: present

#See C:\tools\MinGW\bin\mingw-get.exe
#mingw-get install gcc g++ mingw32-make gdb objc msys-base

#mingw-get install msys-wget msys-zip msys-unzip

#TODO
#- name: "Link 1 to Older mingw32 such as gcc 4.9.0"
#  win_command: mklink /j "C:\tools\msys64\mingw32" "C:\tools\mingw32"'

#export PATH="$PATH:/c/tools/msys64/mingw32/bin"

- name: Ensure that mingw32 are present on the global system path, and in the specified order (OLD)
  win_path:
    elements:
      - 'C:\\tools\\msys64\\mingw32\\bin'
  tags:
    - path
    - mingw32
    - msys2
    - env
    - build
    #- vm # do not install on docker image

- name: Ensure that Msys64 are present on the global system path, and in the specified order (OLD)
  win_path:
    elements:
      - 'C:\\tools\\msys64'
      - 'C:\\tools\\msys64\\usr\\bin'
  tags:
    - path
    - mingw64
    - msys2
    - env
    - build
    #- vm # do not install on docker image

- name: Ensure that Msys64 are present on the global system path, and in the specified order (NEW)
  win_path:
    elements:
      - 'C:\\msys64'
      - 'C:\\msys64\\usr\\bin'
  tags:
    - path
    - mingw64
    - msys2
    - env
    - build
    #- vm # do not install on docker image

- name: "Link SYSTEM USER"
  win_command: 'mklink /j "C:\\tools\\msys64\\home\\SYSTEM" "C:\\tools\\msys64\\home\\fru"'
  tags:
    - package
    #- mingw
    - msys2
    - user
    - mklink
    - custom
    - build
    #- vm # do not install on docker image
#- name: Allow full control to User fru
#  ansible.windows.win_acl:
#    user: fru
#    path:C:\tools\msys64\home\SYSTEM
#    rights: FullControl
#    type: allow
#    rights: ExecuteFile,Write

# TODO in order to test, open a cmd prompt and type bash

#- name: Enable Microsoft-Windows-Subsystem-Linux
#  win_shell: |
#    Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
