---

#this role required msys2 tool

- name: Ensure that Msys64 are present on the global system path, and in the specified order
  win_path:
    elements:
    - 'C:\tools\msys64'
    - 'C:\tools\msys64\usr\bin'

#See inside C:\tools

#pacman -Sy
#pacman -Su

#See https://wiki.archlinux.org/index.php/mirrors

#nano /etc/pacman.conf
#Enable the extra repository on /etc/pacman.conf:
#[extra]
#Server = http://mirrors.kernel.org/archlinux/$repo/os/$arch
#
#[core]
#Server = ftp://ftp.hosteurope.de/mirror/ftp.archlinux.org/core/os/$arch

- name: Create a Unix-style pacman.conf
  win_template:
    src: pacman.conf.j2
    dest: C:\tools\msys64\etc\pacman.conf
    newline_sequence: '\n'
    backup: yes

- name: Upgrade pacman extra repo for lsof
  win_lineinfile:
    path: C:\tools\msys64\etc\pacman.conf
    regexp: '^[extra]'
    line: "{{ item }}"
  with_items: "{{ pacman_extra_repo }}"
  when: pacman_extra_repo | length > 0
  become: true
  become_method: sudo
  tags:
    - pacman

#pacman -Syu --debug

#Refresh package list
# pacman -Syyu

# Run the equivalent of "pacman -Syu" as a separate step
- name: Upgrade pacman
  pacman:
    update_cache: yes
    upgrade: yes
  when: (ansible_os_family != 'Windows' )

- name: Make sure msys2 pacman gcc packages is properly installed
  pacman:
    name: mingw-w64-x86_64-gcc
    state: present
  ignore_errors: true

- name: Make sure msys2 pacman ssl is properly installed for ansible
  pacman:
    name:
      - libcrypt-devel
      - libffi-devel
      - openssl-devel
    state: present
  ignore_errors: true

- name: Install msys2 required build packages
  pacman:
    name:
      - autoconf
      - automake
      - make
      - pkg-config
      - libtool
    state: present
  ignore_errors: true

- name: Install msys2 required editor packages
  win_shell: pacman -Syu nano
  ignore_errors: true

- name: Install msys2 required lsof packages
  win_shell: pacman -Sy glibc lsof  # lsof from extra repo meed glic from core repo
  ignore_errors: true

- name: Install msys2 required rsync packages
  win_shell: pacman -Sy rsync openssh
  ignore_errors: true

#FYI : I had to refresh package list to make ssh working
# pacman -Syyu

- name: Install msys2 required compression packages
  pacman:
    name:
      - zip
      - unzip
    state: present
  ignore_errors: true

#Installing GCC & MSYS2
#See https://github.com/orlp/dev-on-windows/wiki/Installing-GCC--&-MSYS2
#or https://github.com/mangband/mangband/wiki/MSYS2
#pacman -S --needed base-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain \
#                   git subversion mercurial \
#                   mingw-w64-i686-cmake mingw-w64-x86_64-cmake

- name: Install msys2 required git
  win_shell: pacman -Sy git
  ignore_errors: true

- name: Install msys2 required fonts packages
  win_shell: pacman -Sy mingw-w64-x86_64-freetype mingw-w64-x86_64-SDL mingw-w64-x86_64-SDL_ttf
  ignore_errors: true

- name: Install msys2 optional packages
  win_shell: pacman -Sy zsh sh curl
#  ignore_errors: true

#TODO python 3 install
#pacman -S mingw32/mingw-w64-i686-python3-numpy
#pacman -S mingw32/mingw-w64-i686-python3-pip
#pacman -S mingw32/mingw-w64-i686-python3-setuptools
#pacman -S msys/python3-pip
#curl https://bootstrap.pypa.io/ez_setup.py | python
#easy_install pip
#pip install grip
#pip install "pywinrm>=0.3.0"
