
- name: Install python2
  win_chocolatey:
    name: python3
    version: '2.7.14'
    state: present
            
- name: Install python3
  win_chocolatey:
    name: python3
    version: '3.6.2'
    state: present
            
- name: Install pip
  win_chocolatey:
    name: pip
    version: '1.2.0'
    state: present
         
