---
- name: "download scons"
  win_get_url:
    url: "{{ scons.url_prefix }}/{{ scons.installer }}"
    dest: "{{ ansible_user_dir }}\\{{ scons.installer }}"
    force: no
  tags:
    - scons
    - scons230

- name: "install scons"
  win_command: "easy_install {{ ansible_user_dir }}\\{{ scons.installer }}"
  tags:
    - scons
    - scons230

- name: "clean scons installer"
  win_file:
    path: "{{ ansible_user_dir }}\\{{ scons.installer }}"
    state: absent
  tags:
    - cleanup
    - scons
    - scons230

#cd scons-2.5.1
# python setup.py install

#- name: Install pywin32 for scons parallel
#  win_chocolatey:
#    name: pywin32
#    version: '219.0'
#    state: present
#  ignore_errors: true

- name: Initialize ALIAS for MSYS and MINGW64
  win_shell: echo "alias scons=\"/c/Python27/python.exe  /c/Python27/Scripts/scons\"" >> ~/.bashrc
  ignore_errors: true
  tags:
    - python2
    - scons

# See https://stackoverflow.com/questions/25981703/pip-install-fails-with-connection-error-ssl-certificate-verify-failed-certi

# CMD
# call C:\Python27\Scripts\pip2.7.exe uninstall pywin32
# call C:\Python27\Scripts\pip2.7.exe --trusted-host pypi.org --trusted-host files.pythonhosted.org install pywin32==227 distro==1.5.0

# MSYS
# /c/Python27/Scripts/pip2.7.exe --trusted-host pypi.org --trusted-host files.pythonhosted.org install pywin32==227 distro==1.5.0
# /c/Python27/python.exe -m pip --trusted-host pypi.org --trusted-host files.pythonhosted.org install --upgrade pip

- name: Install pywin32==227 distro==1.5.0

  win_shell: pip2 install pywin32==227 distro==1.5.0
  #  win_shell: pip2 install --proxy=http://albandrieu.com:3128 pywin32==227 distro==1.5.0
  tags:
    - python2
    - pywin32
    - distro

# Deprecated
# WORKAROUND, TODO by hand http://fr1cslfrbm0059.misys.global.ad/download/scons/scons-2.4.1.zip
# https://scm-git-eur.misys.global.ad/projects/RISK/repos/fr-arc/browse/Almonde/build.bat#49
- name: Install scons==2.4.1

  win_shell: pip2 install --proxy=http://10.21.185.171:3128 scons==2.4.1
  #  win_shell: pip2 install --proxy=http://albandrieu.com:3128 scons==2.4.1
  register: pip_out
  tags:
    - python2
    - scons

- debug: var=pip_out.stdout_lines
  tags:
    - python2
    - scons
    - debug
