---
- name: "visual studio 2008 : download iso"
  win_get_url:
    url: "{{ visualstudio.url_prefix }}/{{ visualstudio.2008.iso }}"
    dest: "{{ ansible_user_dir }}\\{{ visualstudio.2008.iso }}"
    force: no

- name: "visual studio 2008 : extract files from iso"
  win_command: 7z x -aos -o"{{ visualstudio.2008.installer.path }}" "{{ ansible_user_dir }}\\{{ visualstudio.2008.iso }}"

- name: "visual studio 2008 : copy unattended installation script"
  win_copy:
    src: "{{ visualstudio.2008.installer.ini }}"
    dest: "{{ ansible_user_dir }}\\{{ visualstudio.2008.installer.ini }}"

- name: "visual studio 2008 : unattended installation"
  win_command: "{{ visualstudio.2008.installer.path }}\\setup\\setup.exe /q /norestart"
#   win_command: "{{ visualstudio.2008.installer.path }}\\setup\\setup.exe /unattendfile {{ ansible_user_dir }}\\{{ visualstudio.2008.installer.ini }}"

- name: "visual studio 2008 : clean installation files"
  win_file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_user_dir }}\\{{ visualstudio.2008.iso }}"
    - "{{ ansible_user_dir }}\\{{ visualstudio.2008.installer.ini }}"
    - "{{ visualstudio.2008.installer.path }}"
  tags:
    - cleanup
