---

#choco install visualstudio2017-workload-nativecrossplat --package-parameters "--productId Microsoft.VisualStudio.Product.Enterprise --channelId VisualStudio.15.Release --includeOptional"

- name: Install microsoft-build-tools
  win_chocolatey:
    name: microsoft-build-tools
    version: '15.0.26320.2'
    state: present

- name: Install visualstudio2017 - Build Tools allow you to build native and managed MSBuild-based applications without requiring the Visual Studio IDE.
  win_chocolatey:
    name: visualstudio2017buildtools
    version: '15.9.26.0'
    state: present

- name: Install visualstudio2017 - Visual C++ build tools workload to an existing installation of Visual Studio 2017 Build Tools.
  win_chocolatey:
    name: visualstudio2017-workload-vctools
    version: '1.3.2'
    state: present

#- name: Install vcredist140 : Microsoft Visual C++ Redistributable for Visual Studio 2015-2019 installs run-time components of Visual C++ libraries.
#  win_chocolatey:
#    name: vcredist140
#    version: '14.26.28720.3'
#    state: present

#- name: Install vcredist2015
#  win_chocolatey:
#    name: vcredist140
#    version: '14.0.24215.20170201'
#    state: present

- name: Install visualstudio-installer
  win_chocolatey:
    name: visualstudio-installer
    version: '2.0.2'
    state: present

#choco install vcredist-all
- name: Install vcredist2017
  win_chocolatey:
    name: vcredist2017
    version: '14.16.27033'
    state: present

#- name: Install visualstudio2017community
#  win_chocolatey:
#    name: visualstudio2017community
#    version: '15.9.26.0'
#    state: present

- name: "Link 1 to Visual Studio to avoid spaces"
  win_command: mklink /D "C:\VS" "C:\Program Files (x86)\Microsoft Visual Studio"

#New-Item -ItemType SymbolicLink -Path C:\VS -Target "C:\Program Files (x86)\Microsoft Visual Studio"
