---
# This playbook contains common plays that will be run on all nodes.

- name: Ping
  win_ping:

- name: run ipconfig
  raw: ipconfig
  register: ipconfig
- debug: var=ipconfig

- name: test stat module on file
  win_stat: path="C:/Windows/win.ini"
  register: stat_file

- debug: var=stat_file

- name: check stat_file result
  assert:
      that:
         - "stat_file.stat.exists"
         - "not stat_file.stat.isdir"
         - "stat_file.stat.size > 0"
         - "stat_file.stat.md5"

- name: Add User
  win_user:
    name: jenkins
    password: "Microsoft123$"
    state: present

- name: Save the result of 'whoami' in 'whoami_out'
  win_command: whoami
  register: whoami_out

- debug: var=whoami_out.stdout_lines

- name: Save the result of 'whoami' in 'whoami_out'
  win_shell: echo $PSVersionTable
  register: ps_out

- debug: var=ps_out.stdout_lines

- name: echo 'temp' in 'temp_out'
  win_shell: echo $temp
  register: temp_out

- debug: var=temp_out.stdout_lines

#- name: Copy helloworld.ps1 to TMP
#  win_copy:
#    src: files/helloworld.ps1
#    dest: C:\Windows\Temp
#  register: out
#
#- debug: var=out.stdout_lines
#
#- name: Run powershell script
#  script: C:\Windows\Temp\helloworld.ps1
#  register: out
#
#- debug: var=out.stdout_lines

- name: "Try command choco"
  win_command: choco -v
  register: result
  ignore_errors: true

#- name: "install chocolatey"
#  include: chocolatey.yml
#  when: result|failed
  
#- name: update installed chocolatey packages
#  win_chocolatey:
#    name: all
#    state: latest

- include: common.yml

- include: git.yml

- include: editor.yml

- include: tools.yml

- include: build.yml

- include: perl.yml

- include: cpp.yml

#- include: objc.yml

- include: java.yml

- include: python.yml

- include: javascript.yml

#- include: quality.yml

#- include: admin.yml

#- include: browser.yml

#- include: database.yml

## Install/uninstall an msi-based package
#- name: Install msi-based package (Remote Desktop Connection Manager)
#  win_package:
#    path: "https://download.microsoft.com/download/A/F/0/AF0071F3-B198-4A35-AA90-C68D103BDCCF/rdcman.msi"
#    product_id: "{0240359E-6A4C-4884-9E94-B397A02D893C}"

#See https://docs.ansible.com/ansible/list_of_windows_modules.html

#- name: Install common prerequisite like (GIT, meld, notepadplusplus and zabbix-agent)
#  script: common-setup.ps1

#- name: "reboot"
#  win_reboot:
