---
# This playbook contains common plays that will be run on all nodes.

- name: Ping 
  win_ping:
    
- name: run ipconfig
  raw: ipconfig
  register: ipconfig
- debug: var=ipconfig

- name: test stat module on file
  win_stat: path="C:/Windows/win.ini"
  register: stat_file

- debug: var=stat_file

- name: check stat_file result
  assert:
      that:
         - "stat_file.stat.exists"
         - "not stat_file.stat.isdir"
         - "stat_file.stat.size > 0"
         - "stat_file.stat.md5"

- name: Add User
  win_user:
    name: ansible
    password: "Motdepasse12"

- name: Run powershell script 
  script: helloworld.ps1

- name: Install common prerequisite like (GIT, meld, notepadplusplus and zabbix-agent)
  script: common-setup.ps1
