---
# This playbook contains common plays that will be run on all nodes.

- name: Ping 
  win_ping:
    
- name: run ipconfig
  raw: ipconfig
  register: ipconfig
- debug: var=ipconfig

- name: test stat module on file
  win_stat: path="C:/Windows/win.ini"
  register: stat_file

- debug: var=stat_file

- name: check stat_file result
  assert:
      that:
         - "stat_file.stat.exists"
         - "not stat_file.stat.isdir"
         - "stat_file.stat.size > 0"
         - "stat_file.stat.md5"

- name: Add User
  win_user:
    name: jenkins
    password: "Microsoft123$"
    state: present

#- name: Copy helloworld.ps1 to c:\temp (results in C:\Temp\temp_files)
#  win_copy:
#    src: files/helloworld.ps1
#    dest: C:\TEMP

#- name: Run powershell script 
#  script: C:\TEMP\helloworld.ps1

- include: common.yml

- include: git.yml

- include: editor.yml

- include: tools.yml

- include: build.yml

- include: cpp.yml

#- include: objc.yml

- include: java.yml

- include: python.yml

- include: javascript.yml

#- include: quality.yml

#- include: admin.yml

#- name: Install the vc thingy
#  win_package:
#    name="Microsoft Visual C thingy"
#    path="http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe"
#    Product_Id="{CF2BEA3C-26EA-32F8-AA9B-331F7E34BA97}"
#    Arguments="/install /passive /norestart"
#
## Install/uninstall an msi-based package
#- name: Install msi-based package (Remote Desktop Connection Manager)
#  win_package:
#    path: "https://download.microsoft.com/download/A/F/0/AF0071F3-B198-4A35-AA90-C68D103BDCCF/rdcman.msi"
#    product_id: "{0240359E-6A4C-4884-9E94-B397A02D893C}"
    
#See https://docs.ansible.com/ansible/list_of_windows_modules.html

#- name: Install common prerequisite like (GIT, meld, notepadplusplus and zabbix-agent)
#  script: common-setup.ps1
