---
# This playbook contains common plays that will be run on all nodes.

- name: Ping
  win_ping:

- name: run ipconfig
  raw: ipconfig
  register: ipconfig
- debug: var=ipconfig

- name: test stat module on file
  win_stat: path="C:/Windows/win.ini"
  register: stat_file

- debug: var=stat_file

- name: check stat_file result
  assert:
    that:
      - "stat_file.stat.exists"
      - "not stat_file.stat.isdir"
      - "stat_file.stat.size > 0"

- name: Add User
  win_user:
    name: jenkins
    password: "Jenkins123$"
    state: present

- name: Save the result of 'whoami' in 'whoami_out'
  win_command: whoami
  register: whoami_out

- debug: var=whoami_out.stdout_lines

- name: Save the result of 'whoami' in 'whoami_out'
  win_shell: echo $PSVersionTable
  register: ps_out

- debug: var=ps_out.stdout_lines

- name: echo 'temp' in 'temp_out'
  win_shell: echo $TEMP
  register: temp_out

- debug: var=temp_out.stdout_lines

- name: Create temp directory
  win_file:
    path: C:\Windows\Temp
    state: directory

- name: Copy helloworld.ps1 to TMP
  win_copy:
    src: files/helloworld.ps1
    dest: C:\Windows\Temp\helloworld.ps1
    force: True
    remote_src: False
    register: out
  tags:
    - helloworld

- debug: var=out.stdout_lines
  tags:
    - helloworld

- debug:
    msg: set-executionpolicy remotesigned
  tags:
    - security

- name: "Check executionpolicy"
  win_shell: Get-ExecutionPolicy
  tags:
    - security

- name: "Change ExecutionPolicy"
  win_command: Set-ExecutionPolicy AllSigned
  ignore_errors: true
  tags:
    - security

#- name: Run powershell script
#  script: C:\Windows\Temp\helloworld.ps1
#  register: out

- name: Run powershell script
  script: files/helloworld.ps1
  register: out
  tags:
    - helloworld
    - debug

- debug: var=out.stdout_lines
  tags:
    - helloworld
    - debug

- name: Set an http_proxy environment variable for all users
  win_environment:
    state: present
    name: http_proxy
    value: http://10.21.185.171:3128
    level: machine

- name: Set an http_proxy environment variable for all users
  win_environment:
    state: present
    name: https_proxy
    value: http://10.21.185.171:3128
    level: machine

- name: Set an http_proxy environment variable for all users
  win_environment:
    state: present
    name: no_proxy
    value: localhost,127.0.0.1,.finastra.com,.misys.global.ad,.finastra.global,.azurecr.io,verdaccio,10.199.52.11,alm-npmjs,bm-artifacts,alm-artifacts,verdaccio,.microsoft.com,amazonaws.com,ftp.hosteurope.de,mirrors.kernel.org
    level: machine

- name: "Try command choco"
  win_command: choco -v
  register: result
  ignore_errors: true

  tags:
    - chocolatey

#- name: "install chocolatey"
#  import_tasks: chocolatey.yml
#  when: result|failed

- name: "Upgrade chocolatey"
  win_command: choco upgrade chocolatey -y

  tags:
    - chocolatey
    - upgrade

- name: "Installl chocolateygui"

  win_command: choco install chocolateygui -y

  tags:
    - chocolatey
    - upgrade
#  ignore_errors: true

#- name: update installed chocolatey packages
#  win_chocolatey:
#    name: all
#    state: latest

#choco install chocolatey-core.extension -y
#- name: Install activeperl
#  win_chocolatey:
#    name: chocolatey-core.extension
#    state: present

#- import_tasks: windows-diskE.yml

- import_tasks: common.yml

- import_tasks: python.yml
- import_tasks: git.yml

#- import_tasks: svn.yml

- import_tasks: editor.yml

- import_tasks: tools.yml

- import_tasks: build.yml

- import_tasks: pacman.yml
  tags:
    - package
    - pacman
    - build

- import_tasks: perl.yml
  tags:
    - package
    - perl
    - build

- import_tasks: cpp.yml

#- import_tasks: objc.yml
#  tags:
#    - objc

- import_tasks: java.yml

- import_tasks: python.yml

#- import_tasks: scons.yml

- import_tasks: javascript.yml

#- import_tasks: quality.yml

#- import_tasks: admin.yml

#- import_tasks: browser.yml

- name: "Install database driver"
  import_tasks: database.yml
  tags:
    - sqlserver
    - driver-database

- name: "Install SqlServer management studio"
  import_tasks: sqlserver.yml
  tags:
    - sqlserver
    - sqlserver-database

#- import_tasks: openssl.yml

- import_tasks: user.yml

#- import_tasks: debug.yml

- import_tasks: docker.yml
  tags:
    - docker

- import_tasks: kubernetes.yml
  tags:
    - kubernetes

- import_tasks: security.yml
  tags:
    - security

- import_tasks: azure.yml
  tags:
    - azure
## Install/uninstall an msi-based package
#- name: Install msi-based package (Remote Desktop Connection Manager)
#  win_package:
#    path: "https://download.microsoft.com/download/A/F/0/AF0071F3-B198-4A35-AA90-C68D103BDCCF/rdcman.msi"
#    product_id: "{0240359E-6A4C-4884-9E94-B397A02D893C}"

#See https://docs.ansible.com/ansible/list_of_windows_modules.html

#- name: Install common prerequisite like (GIT, meld, notepadplusplus and zabbix-agent)
#  script: common-setup.ps1

# Only for Windows Server 2012 (not neededed for Windows Server 2016), you need to change DEP.
#
# Go in « Control panel / System »,
# Then « Advanced system settings »,
# Then in tab « Advanced / Performances », click on « Settings »,
# Then in tab  « Data Execution Prevention », tick the first option, « Turn on DEP for essential Windows programs and services only »,
# Reboot

#- name: "reboot"
#  win_reboot:
